### ISSUE TITLE
Duration fluctuates during playback of MP4/AAC+

### ISSUE THREAD

**Issue by daegloe** [alexcrichton/AudioStreamer#20] opened 2012-10-30 07:11 UTC
The duration of the song fluctuates during the first few seconds of MP4/AAC+ playback, and sometimes longer.

I can see why this might happen with an MP3 file that may not contain the appropriate/correct headers and/or may be truncated, but an MP4 should have the necessary atoms (mvhd, tkhd), to calculate an exact duration in advance of the actual audio playback.

Thoughts?

**Comment by Bo98** [comment] 2015-02-11 16:10
Progress and duration calculations should now be very accurate for the files we can get the data for. There should be no margin of error or fluctuation anymore for files with the proper headers (MP3/M4A etc.) or if they are CBR (constant bitrate). Even for raw AAC files where it does not contain the duration in the headers there is a lot less fluctuation now. From my testing it only fluctuates by up to 0.4 seconds depending on how even the stream starts. On a perfect stream the fluctuation can be just up to 0.1 seconds. If you do not show fractions of seconds then the fluctuation should be invisible in most cases. There is a couple second margin of error however because we don't get the data offsets for raw AAC. I'm not sure if much can be done about it. How we nearly get the duration is quite good. iTunes and such don't even show it.

Seeking has also drastically improved. It should work just about perfect now.

**Comment by Bo98** [comment] 2018-04-14 18:00
There's been a few more improvements since then. Most recently including a fix for large files due to an inaccuracy caused by integer division.

I'm happy with the amount of improvements here. Should I find anything else by chance, I will address it. But unless anyone is aware of a specific file which there are still issues with, I will close this issue for now as the issue has been resolved for most files I've come across.

**Closed by Bo98** 2018-04-14 18:00 UTC
Labels: bug
